apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: gueka/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gueka/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: gueka/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gueka/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gueka/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: gueka/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .


## GCLOUD CONFIG
#apiVersion: skaffold/v2alpha3
#kind: Config
#deploy:
#  kubectl:
#    manifests:
#      - ./infra/k8s/*
#build:
#   local:
#     push: false
#  googleCloudBuild:
#    projectId: ticketing-dev-372913
#  artifacts:
#    - image: us.gcr.io/ticketing-dev-372913/auth
#      context: auth
#      docker:
#        dockerfile: Dockerfile
#      sync:
#        manual:
#          - src: 'src/**/*.ts'
#            dest: .
